### PR TITLE
Fix 527

### PR DESCRIPTION
**Pull request by kugel-**
Fix for https://github.com/ffi/ffi/issues/527 based on your patch. I attempted to workaround OSX, can you check this?

### CODE REVIEW

**Comment by kugel-** [comment]
appveyor didn't build but it never has. Should I pay attention?

**Comment by larskanis** [comment]
@kugel- Thanks for working on this issue! It looks good to me. Don't bother with appveyor. I did a ffi spec run locally on Ruby-2.4 on Windows-10 and it didn't show any errors. So if I find the time, I'll fix it. But for now it's unrelated.

 The more interesting part is to do some checks of ffi->fiddle and vice versa. Are you working on this?

**Comment by kugel-** [comment]
I'm working on a test yes. I just wonder how to involve fiddle (if at all)? 

My current plan is to re-use my program from https://github.com/ffi/ffi/issues/527 and transform it into a test case (i.e. exec()'ing it from a test script and observing if it hangs). I'm new to rspec and friends so I'm open for suggestions.

**Comment by larskanis** [comment]
The root cause for blocking callbacks is the use of a call frame to save the state of the GVL. This call frame is specific to ffi on MRI. Calling ruby code from C by ffi-callbacks hangs, when the callback is called with no active call frame. This happens when the ffi-callback is called from an embedded ruby process or when the C code is invoked by fiddel or by a C-extension. Since all 3 options could be used to verify the "no-call-frame" situation, I would choose the one that is the most easy to write and to integrate.

Fiddle can use an arbitrary function from the libtest library which is already there and no separate compiler runs are required. This is why I would choose fiddle.

**Comment by kugel-** [comment]
Okay. I've got a question. The test suite runs in a single process right? The problem I'm solving is a deadlock, so in case of a failed test the suite would deadlock. What options to recover are there, if not exec()ing a separate process?

**Comment by larskanis** [comment]
Maybe by the timeout library like this:
```ruby
  require "timeout"
  Timeout.timeout(5) do
    deadlock
  end
```
or if it doesn't work due to the GVL:
```ruby
  it "shouldn't deadlock" do
    if ENV["deadlocktest"]
      deadlock
    else
      # Run the test within its own process to not block the main thread
      pid = spawn({"deadlocktest"=>"1"}, "rspec", "#{__FILE__}:#{__LINE__}")
      begin
        Timeout.timeout(5){ Process.wait(pid) }
      rescue Timeout::Error
        Process.kill(9, pid)
        raise
      end
    end
  end
```

**Comment by larskanis** [comment]
I updated the spawn call to the Array form of the command to avoid spawning a subshell.

**Comment by kugel-** [comment]
@larskanis I'm having the problem that the C code doesn't load the correct gem when it does `require 'ffi'`. Is GEM_HOME/_PATH not correctly set during `rake test`?

**Pull request closed without merging**
